# notebook_01_data_loading.py
# Smart Solar Management - Big Data Project
#
# Loads all raw datasets into PySpark DataFrames and produces a pre-processing
# audit: row counts, null counts, duplicate counts, and basic descriptive stats.
# Run this before notebook_02 to confirm the data is present and well-formed.
#
# Geographic anchor: Gandikota, Andhra Pradesh, India (14.81 N, 78.29 E).
# All three sources below are tied to this location or its surrounding region.
#
# Dataset A - Kaggle Solar Power Generation (CC0)
#   Plant 1 and Plant 2 generation + weather sensor CSVs.
#   Download: kaggle datasets download -d anikannal/solar-power-generation-data
#
# Dataset B - NASA POWER (NASA Open Data, no key required)
#   Hourly irradiance and meteorology for 5 Andhra Pradesh cities, 2016-2024.
#   Generated by: python download_nasa_power.py
#
# Dependencies: pip install pyspark pvlib pandas matplotlib seaborn

# -- Session setup -----------------------------------------------------------

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
import pandas as pd
import os
import glob

spark = (SparkSession.builder
         .appName("SmartSolar_01_DataLoading")
         .config("spark.sql.repl.eagerEval.enabled", True)
         .getOrCreate())

print(f"Spark {spark.version} ready")

# -- Dataset A: Kaggle generation data ---------------------------------------
# Source:  https://www.kaggle.com/datasets/anikannal/solar-power-generation-data
# License: CC0 Public Domain
# The two plant CSVs have the same schema and are unioned into a single frame.

gen_p1 = spark.read.csv("data/raw/Plant_1_Generation_Data.csv",
                         header=True, inferSchema=True)
gen_p2 = spark.read.csv("data/raw/Plant_2_Generation_Data.csv",
                         header=True, inferSchema=True)
wx_p1  = spark.read.csv("data/raw/Plant_1_Weather_Sensor_Data.csv",
                         header=True, inferSchema=True)
wx_p2  = spark.read.csv("data/raw/Plant_2_Weather_Sensor_Data.csv",
                         header=True, inferSchema=True)

gen_df     = gen_p1.unionByName(gen_p2)
weather_df = wx_p1.unionByName(wx_p2)

print("\n=== Dataset A: Generation (Both Plants) ===")
print(f"Rows: {gen_df.count():,}")
gen_df.printSchema()
gen_df.show(5, truncate=False)

print("\n=== Dataset A: Weather Sensors (Both Plants) ===")
print(f"Rows: {weather_df.count():,}")
weather_df.printSchema()
weather_df.show(5, truncate=False)

# -- Dataset B: NASA POWER ---------------------------------------------------
# Source:  https://power.larc.nasa.gov (NASA Langley Research Center)
# License: NASA Open Data - free, unrestricted
# 45 per-city-year CSVs are generated by download_nasa_power.py.
# The combined.csv (if present) is excluded here; individual files are loaded
# and unioned so CITY and YEAR columns remain consistent across all rows.

nasa_files = sorted(glob.glob("data/raw/nasa_power/*.csv"))
nasa_files = [f for f in nasa_files if "combined" not in f]
print(f"\nFound {len(nasa_files)} NASA POWER CSV files")

nasa_parts = []
for fpath in nasa_files:
    basename = os.path.basename(fpath)
    city = basename.split("_")[0]
    year = basename.split("_")[1].replace(".csv", "")
    df = (spark.read
              .option("header", True)
              .option("inferSchema", True)
              .csv(fpath)
          .withColumn("CITY", F.lit(city))
          .withColumn("YEAR", F.lit(int(year))))
    nasa_parts.append(df)

nasa_df = nasa_parts[0]
for part in nasa_parts[1:]:
    nasa_df = nasa_df.unionByName(part, allowMissingColumns=True)

print("\n=== Dataset B: NASA POWER (5 Indian Cities, 2016-2024) ===")
print(f"Rows: {nasa_df.count():,}")
nasa_df.printSchema()
nasa_df.show(5, truncate=False)

# -- Null count audit (before preprocessing) ---------------------------------
from pyspark.sql.functions import col, count, when, isnan

print("\n" + "=" * 60)
print("NULL COUNT SUMMARY - BEFORE Preprocessing")
print("=" * 60)

datasets = [
    ("Generation", gen_df),
    ("Weather",    weather_df),
    ("NASA POWER", nasa_df),
]

for name, df in datasets:
    numeric_cols = [f.name for f in df.schema.fields
                    if str(f.dataType) in ("DoubleType()", "FloatType()", "IntegerType()")]
    null_expr = [
        count(when(
            col(c).isNull() | (isnan(col(c)) if c in numeric_cols else F.lit(False)), c
        )).alias(c)
        for c in df.columns
    ]
    null_counts = df.select(null_expr)
    print(f"\n--- {name} ---")
    null_counts.show(truncate=False)

# -- Duplicate count audit (before preprocessing) ----------------------------
print("\n" + "=" * 60)
print("DUPLICATE ROW COUNTS - BEFORE Preprocessing")
print("=" * 60)

for name, df in datasets:
    total  = df.count()
    unique = df.dropDuplicates().count()
    dupes  = total - unique
    pct    = (dupes / total * 100) if total > 0 else 0
    print(f"  {name:<14}: {total:>8,} total | {unique:>8,} unique | "
          f"{dupes:>5,} duplicates ({pct:.2f}%)")

# -- Basic descriptive statistics (before preprocessing) ---------------------
print("\n" + "=" * 60)
print("DESCRIPTIVE STATISTICS - BEFORE Preprocessing")
print("=" * 60)

print("\nGeneration - DC/AC Power and Yield:")
gen_df.select("DC_POWER", "AC_POWER", "DAILY_YIELD", "IRRADIATION").describe().show()

print("\nNASA POWER - Irradiance and Meteorology:")
nasa_df.select("ghi", "dhi", "dni", "temp_air", "wind_speed",
               "SOLAR_ZENITH_ANGLE", "OPTIMAL_TILT").describe().show()

# -- Combined row count ------------------------------------------------------
print("\n" + "=" * 60)
print("TOTAL ROW COUNTS ACROSS ALL DATASETS")
print("=" * 60)
total_rows = sum(df.count() for _, df in datasets)
for name, df in datasets:
    r = df.count()
    print(f"  {name:<14}: {r:>8,} rows")
print(f"  {'TOTAL':<14}: {total_rows:>8,} rows")
print("=" * 60)

if total_rows >= 500_000:
    print(f"Requirement met: {total_rows:,} >= 500,000 rows")
else:
    print(f"Warning: only {total_rows:,} rows - need more data")

print("\nNotebook 01 complete. Proceed to notebook_02_preprocessing.py")
